name: Windows RDP with LocalXpose and Filebase

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours

jobs:
  windows-rdp:
    runs-on: windows-latest
    timeout-minutes: 360  # 6 hours max
    steps:
      - name: 🧾 Setup Environment
        run: |
          $env:RDP_USER = "rdpuser"
          $env:RDP_PASSWORD = "MySecurePass123!"
          echo "USERNAME=$env:RDP_USER" >> $env:GITHUB_ENV
          echo "PASSWORD=$env:RDP_PASSWORD" >> $env:GITHUB_ENV

      - name: 💾 Download and Setup LocalXpose
        run: |
          Invoke-WebRequest -Uri "https://localxpose.io/downloads/localxpose-windows-amd64.exe" -OutFile "localxpose.exe"
          Start-Sleep -Seconds 2
          .\localxpose.exe login --auth-token $Env:LOCALXPOSE_AUTH_TOKEN
        env:
          LOCALXPOSE_AUTH_TOKEN: ${{ secrets.LOCALXPOSE_AUTH_TOKEN }}

      - name: 🌐 Start LocalXpose RDP Tunnel (gamingrdp)
        run: |
          Start-Process -NoNewWindow -FilePath "localxpose.exe" -ArgumentList "tunnel rdp --subdomain gamingrdp" 

      - name: 👤 Create RDP User
        run: |
          net user $Env:USERNAME $Env:PASSWORD /add
          net localgroup administrators $Env:USERNAME /add
          reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: 📦 Install 7-Zip and AWS CLI
        run: |
          choco install 7zip awscli -y

      - name: 🗃️ Restore from Filebase (if backup exists)
        run: |
          mkdir backup
          aws configure set aws_access_key_id $env:FILEBASE_ACCESS_KEY
          aws configure set aws_secret_access_key $env:FILEBASE_SECRET_KEY
          aws configure set default.region us-east-1
          aws s3 cp s3://$env:FILEBASE_BUCKET/system-backup.zip backup/system-backup.zip || echo "No backup yet"
          if (Test-Path "backup/system-backup.zip") {
            Expand-Archive -Path backup/system-backup.zip -DestinationPath C:\ -Force
          }
        env:
          FILEBASE_ACCESS_KEY: ${{ secrets.FILEBASE_ACCESS_KEY }}
          FILEBASE_SECRET_KEY: ${{ secrets.FILEBASE_SECRET_KEY }}
          FILEBASE_BUCKET: ${{ secrets.FILEBASE_BUCKET }}

      - name: 🔄 Auto Backup Loop (every 30 min)
        run: |
          Start-Job -ScriptBlock {
            while ($true) {
              Compress-Archive -Path "C:\Users\$env:USERNAME" -DestinationPath "C:\backup.zip" -Force
              aws s3 cp C:\backup.zip s3://$env:FILEBASE_BUCKET/system-backup.zip --region us-east-1
              Start-Sleep -Seconds 1800  # 30 minutes
            }
          }
        env:
          FILEBASE_ACCESS_KEY: ${{ secrets.FILEBASE_ACCESS_KEY }}
          FILEBASE_SECRET_KEY: ${{ secrets.FILEBASE_SECRET_KEY }}
          FILEBASE_BUCKET: ${{ secrets.FILEBASE_BUCKET }}

      - name: 💤 Keep Session Alive
        run: timeout /t 21500
